// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neklbjazaytbtadkwjmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5la2xiamF6YXl0YnRhZGt3am1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjAzNDUsImV4cCI6MjA3NDEzNjM0NX0.ZCnjMXbxxi30xVfT6-6h35gkbmzUwRe1L6YT6A-N5xw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});